# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19jZtCyyzFj6k34fsG52HcQxoKslEZlYY
"""

# app.py

import streamlit as st
import pandas as pd
import joblib
from scipy.sparse import hstack

# =====================================
# LOAD ARTIFACTS
# =====================================

model = joblib.load("sia_xgboost.pkl")
tfidf = joblib.load("tfidf.pkl")
scaler = joblib.load("scaler.pkl")

channel_encoder = joblib.load(
    "channel_encoder.pkl"
)

category_encoder = joblib.load(
    "category_encoder.pkl"
)

# =====================================
# PAGE CONFIG
# =====================================

st.set_page_config(
    page_title="Support Integrity Auditor",
    page_icon="🎯",
    layout="wide"
)

st.title("🎯 Support Integrity Auditor")
st.markdown(
    """
    Detect priority mismatches in customer support tickets
    using NLP and Machine Learning.
    """
)

# =====================================
# USER INPUTS
# =====================================

ticket_id = st.text_input(
    "Ticket ID",
    "TKT-001"
)

ticket_subject = st.text_input(
    "Ticket Subject"
)

ticket_description = st.text_area(
    "Ticket Description",
    height=200
)

ticket_channel = st.selectbox(
    "Ticket Channel",
    list(channel_encoder.classes_)
)

issue_category = st.selectbox(
    "Issue Category",
    list(category_encoder.classes_)
)

resolution_time = st.number_input(
    "Resolution Time (Hours)",
    min_value=0.0,
    value=24.0
)

satisfaction_score = st.slider(
    "Satisfaction Score",
    1,
    5,
    3
)

# =====================================
# ENCODING FUNCTION
# =====================================

def safe_transform(encoder, value):

    mapping = {
        cls: idx
        for idx, cls in enumerate(
            encoder.classes_
        )
    }

    return mapping.get(value, -1)

# =====================================
# PREDICT BUTTON
# =====================================

if st.button("Analyze Ticket"):

    combined_text = (
        ticket_subject
        + " "
        + ticket_description
    )

    word_count = len(
        combined_text.split()
    )

    channel_enc = safe_transform(
        channel_encoder,
        ticket_channel
    )

    category_enc = safe_transform(
        category_encoder,
        issue_category
    )

    # TF-IDF

    X_text = tfidf.transform(
        [combined_text]
    )

    # Metadata

    metadata = pd.DataFrame(
        [[
            resolution_time,
            satisfaction_score,
            channel_enc,
            category_enc,
            word_count
        ]],
        columns=[
            "Resolution_Time_Hours",
            "Satisfaction_Score",
            "channel_enc",
            "category_enc",
            "word_count"
        ]
    )

    metadata_scaled = scaler.transform(
        metadata
    )

    X = hstack([
        X_text,
        metadata_scaled
    ])

    probability = model.predict_proba(
        X
    )[0][1]

    prediction = int(
        probability > 0.40
    )

    # =====================================
    # RESULT
    # =====================================

    st.markdown("---")

    st.subheader(
        "Prediction Result"
    )

    if prediction == 1:

        st.error(
            "⚠️ Priority Mismatch Detected"
        )

        mismatch_type = (
            "Hidden Crisis"
        )

    else:

        st.success(
            "✅ Priority Appears Consistent"
        )

        mismatch_type = (
            "Priority Consistent"
        )

    st.metric(
        "Confidence Score",
        f"{probability:.2%}"
    )

    # =====================================
    # DOSSIER
    # =====================================

    st.subheader(
        "Evidence Dossier"
    )

    dossier = {

        "ticket_id":
            ticket_id,

        "predicted_mismatch":
            prediction,

        "mismatch_type":
            mismatch_type,

        "feature_evidence":[

            {
                "signal":
                    "resolution_time",

                "value":
                    resolution_time
            },

            {
                "signal":
                    "satisfaction_score",

                "value":
                    satisfaction_score
            },

            {
                "signal":
                    "ticket_length",

                "value":
                    word_count
            }

        ],

        "confidence":
            round(
                float(probability),
                4
            )
    }

    st.json(dossier)

# =====================================
# SIDEBAR
# =====================================

st.sidebar.title("Project Info")

st.sidebar.info(
    """
    Support Integrity Auditor (SIA)

    Model:
    XGBoost Classifier

    Features:
    • TF-IDF Text Features
    • Resolution Time
    • Satisfaction Score
    • Ticket Channel
    • Issue Category

    Output:
    • Priority Mismatch Detection
    • Evidence Dossier
    """
)