# -*- coding: utf-8 -*-
"""predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nmIrao5hLmq-X_EfNLYREPa1kb5Sqlga
"""

# predict.py

import pandas as pd
import numpy as np
import joblib
import json

from scipy.sparse import hstack

# =====================================================
# LOAD ARTIFACTS
# =====================================================

print("Loading models...")

model = joblib.load("sia_xgboost.pkl")
tfidf = joblib.load("tfidf.pkl")

channel_encoder = joblib.load(
    "channel_encoder.pkl"
)

category_encoder = joblib.load(
    "category_encoder.pkl"
)

scaler = joblib.load("scaler.pkl")

# =====================================================
# INPUT CSV
# =====================================================

INPUT_FILE = "input_tickets.csv"

df = pd.read_csv(INPUT_FILE)

print(f"Loaded {len(df)} tickets")

# =====================================================
# TEXT CREATION
# =====================================================

df["combined_text"] = (
    df["Ticket_Subject"].fillna("")
    + " "
    + df["Ticket_Description"].fillna("")
)

# =====================================================
# BASIC FEATURES
# =====================================================

df["word_count"] = (
    df["combined_text"]
    .str.split()
    .apply(len)
)

# =====================================================
# ENCODE METADATA
# =====================================================

def safe_transform(encoder, series):

    mapping = {
        cls: idx
        for idx, cls in enumerate(
            encoder.classes_
        )
    }

    return series.map(
        lambda x: mapping.get(x, -1)
    )

df["channel_enc"] = safe_transform(
    channel_encoder,
    df["Ticket_Channel"]
)

df["category_enc"] = safe_transform(
    category_encoder,
    df["Issue_Category"]
)

# =====================================================
# TF-IDF
# =====================================================

X_text = tfidf.transform(
    df["combined_text"]
)

# Get the number of features the model expects in total.
expected_total_features = model.get_booster().num_features()

# The metadata contributes 5 features, so X_text should contribute the rest.
# This assumes the number of metadata features is constant at 5.
expected_X_text_features = expected_total_features - 5

# Adjust X_text if its feature count mismatches
if X_text.shape[1] != expected_X_text_features:
    print(f"Warning: TF-IDF feature count mismatch. Expected {expected_X_text_features}, got {X_text.shape[1]}. Adjusting...")
    if X_text.shape[1] > expected_X_text_features:
        X_text = X_text[:, :expected_X_text_features] # Truncate if too many features
    else:
        # This case is not the one causing the current error.
        # If X_text has fewer features, padding with zeros might be an option,
        # but it depends on the context and could introduce issues.
        raise ValueError(f"TF-IDF transformed text has fewer features ({X_text.shape[1]}) than expected ({expected_X_text_features}). Cannot proceed without proper padding or re-training TF-IDF.")

# =====================================================
# METADATA
# =====================================================

metadata = df[
    [
        "Resolution_Time_Hours",
        "Satisfaction_Score",
        "channel_enc",
        "category_enc",
        "word_count"
    ]
]

metadata_scaled = scaler.transform(
    metadata
)

# =====================================================
# FINAL FEATURE MATRIX
# =====================================================

X = hstack([
    X_text,
    metadata_scaled
])

# =====================================================
# PREDICTIONS
# =====================================================

probabilities = model.predict_proba(X)[:,1]

predictions = (
    probabilities > 0.40
).astype(int)

df["Mismatch_Prediction"] = predictions

df["Confidence"] = probabilities

# =====================================================
# DOSSIER GENERATION
# =====================================================

def generate_dossier(row):

    mismatch_type = (
        "Priority Mismatch"
        if row["Mismatch_Prediction"] == 1
        else "Priority Consistent"
    )

    dossier = {

        "ticket_id":
            str(row["Ticket_ID"]),

        "assigned_priority":
            str(
                row.get(
                    "Priority_Level",
                    "Unknown"
                )
            ),

        "predicted_mismatch":
            int(
                row["Mismatch_Prediction"]
            ),

        "mismatch_type":
            mismatch_type,

        "feature_evidence":[

            {
                "signal":
                    "resolution_time",

                "value":
                    float(
                        row[
                            "Resolution_Time_Hours"
                        ]
                    ),

                "interpretation":
                    "Higher resolution time may indicate greater severity"
            },

            {
                "signal":
                    "satisfaction_score",

                "value":
                    float(
                        row[
                            "Satisfaction_Score"
                        ]
                    ),

                "interpretation":
                    "Lower satisfaction may indicate severe issue"
            },

            {
                "signal":
                    "ticket_length",

                "value":
                    int(
                        row["word_count"]
                    ),

                "interpretation":
                    "Longer tickets often contain more issue details"
            }

        ],

        "constraint_analysis":

            f"""
            Ticket was analyzed using textual
            content and structured metadata.
            The classifier detected
            {'a potential priority mismatch'
            if row['Mismatch_Prediction']==1
            else 'no significant mismatch'}.
            """.strip(),

        "confidence":
            round(
                float(
                    row["Confidence"]
                ),
                4
            )
    }

    return dossier

# =====================================================
# CREATE DOSSIERS
# =====================================================

dossiers = []

for _, row in df.iterrows():

    dossiers.append(
        generate_dossier(row)
    )

# =====================================================
# SAVE OUTPUTS
# =====================================================

df.to_csv(
    "predictions.csv",
    index=False
)

with open(
    "evidence_dossiers.json",
    "w"
) as f:

    json.dump(
        dossiers,
        f,
        indent=4
    )

print("Predictions Saved")

print("Evidence Dossiers Saved")

print("""
Generated Files:

1. predictions.csv
2. evidence_dossiers.json
""")