# -*- coding: utf-8 -*-
"""train_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zIyuXodIdwcHjMBoUL2QZZojKILs2CLT
"""

import pandas as pd
import joblib

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier

# Load Data
df = pd.read_csv("pseudo_labeled_dataset.csv")

# Features
X_text = df["clean_text"]
y = df["Mismatch_Label"]

# TF-IDF
tfidf = TfidfVectorizer(
    max_features=15000,
    ngram_range=(1,2)
)

X = tfidf.fit_transform(X_text)

# Split
X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Model
model = XGBClassifier(
    n_estimators=500,
    max_depth=8,
    learning_rate=0.05,
    random_state=42
)

model.fit(X_train,y_train)

# Save
joblib.dump(model,"sia_xgboost.pkl")
joblib.dump(tfidf,"tfidf.pkl")

print("Training Complete")